Tarefas/Models/TarefaViewModel.cs
using System.Collections.Generic;

namespace Tarefas.Models
{
    public class TarefaViewModel
    {
        public IEnumerable<TarefaItem> TarefaItens {get;set;}
    }
}

Tarefas/Controllers/TarefasController.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Tarefas.Models;
using Tarefas.Services;

namespace Tarefas.Controllers
{
    [Authorize]
    public class TarefasController : Controller
    {
        private readonly ITarefaItemService _tarefaItemService;
        private readonly UserManager<ApplicationUser> _userManager;

        public TarefasController(ITarefaItemService tarefaItemService, UserManager<ApplicationUser> userManager)
        {
            _tarefaItemService = tarefaItemService;
            _userManager = userManager;
        }

        public async Task<IActionResult> Index(bool? criterio)
        {
            ViewData["Title"] = "Gerenciar lista de tarefas";

            //Pegando os dados do usuário logado atual  
            var currentUser = await _userManager.GetUserAsync(User);
            //Challenge redireciona para a página de login novamente
            if(currentUser == null)
                return Challenge();
            
            //obter itens da tarefa
            return View(new TarefaViewModel
            {
                
                TarefaItens = await _tarefaItemService.GetItemAsync(criterio, currentUser)
            });
        }

        [HttpGet]
        public IActionResult AdicionarItemTarefa() => View();

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AdicionarItemTarefa([Bind("Id,EstaCompleta,Nome,DataConclusao")] TarefaItem tarefa)
        {
            //Este Bind informa quais campos o DataBind deve vincular, só será permitido a injeção na tarefa desses 4 campos
            //O Bind é uma maneira de restringir, proteger.
            if (ModelState.IsValid)
            {
                var currentUser = await _userManager.GetUserAsync(User);
                if(currentUser == null)
                    return Challenge();

                tarefa.OwnerId = currentUser.Id;
                await _tarefaItemService.AdicionarItemAsync(tarefa);
                return RedirectToAction(nameof(Index));
            }

            return View(tarefa);
        }

        //GET tarefas/delete/5
        public IActionResult Delete(int? id)
        {
            if (id == null)
                return NotFound();

            var tarefaItem = _tarefaItemService.GetTarefaById(id);
            if (tarefaItem == null)
                return NotFound();

            return View(tarefaItem);
        }

        //Esta Ation name é uma espécie de rota, será levada em conta o Nome "Delete"
        //Ao chamar o método ao invés do nome "DeleteConfirmed"
        [HttpPost]
        [ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            await _tarefaItemService.DeletarItem(id);
            return RedirectToAction(nameof(Index));
        }

        //GET Tarefas/Edit/10
        public IActionResult Edit(int? id)
        {
            if (id == null)
                return NotFound();

            var tarefaItem = _tarefaItemService.GetTarefaById(id);
            if (tarefaItem == null)
                return NotFound();

            return View(tarefaItem);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,EstaCompleta,Nome,DataConclusao")] TarefaItem tarefaItem)
        {
            if (id != tarefaItem.Id)
                return NotFound();

            var currentUser = await _userManager.GetUserAsync(User);
            if(currentUser == null)
                return Challenge();

            if (ModelState.IsValid)
            {
                try
                {
                    await _tarefaItemService.UpdateAsync(tarefaItem, currentUser);
                }
                catch (DbUpdateConcurrencyException) //Tratamento de concorrência (2 usuários editando ao mesmo tempo)
                {
                    throw;
                }

                return RedirectToAction(nameof(Index));
            }

            return View(tarefaItem);
        }
    }
}

Tarefas/Views/Tarefas/AdicionarItemTarefa.cshtml
@model TarefaItem

<h2>Criar Nova Tarefa</h2>
<hr/>

<div class="row">
    <div class="col-md-4">
        <form asp-action="AdicionarItemTarefa" asp-controller="Tarefas" method="POST">
            @*Div de erro*@
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <div class="form-group">
                <label asp-for="Nome" class="control-label"></label>
                <input asp-for="Nome" class="form-control"/>
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="DataConclusao" class="control-label"></label>
                <input asp-for="DataConclusao" class="form-control"/>
                <span asp-validation-for="DataConclusao" class="text-danger"></span>
            </div>

            <div class="form-group">
                <input type="submit" value="Criar Tarefa" class="btn btn-success"/>
            </div>
        </form>
    </div>
</div>
<div>
    <a asp-action="Index">Retornar</a>
</div>

Tarefas/Views/Tarefas/Delete.cshtml
@model TarefaItem

<html>
    <head>
        <meta name="viewport" content="width=device-width"/>
        <title>Deletar tarefa</title>
    </head>

    <body>
        <dl class="horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.EstaCompleta)
            </dt>    
            <dd>
                @Html.DisplayFor(model => model.EstaCompleta)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.Nome)
            </dt>    
            <dd>
                @Html.DisplayFor(model => model.Nome)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.DataConclusao)
            </dt>    
            <dd>
                @Html.DisplayFor(model => model.DataConclusao)
            </dd>
        </dl>
        
        <form asp-action="Delete">
            <input type="hidden" asp-for="Id"/>
            <input type="submit" value="Deletar Tarefa" class="btn btn-danger"/> | 
            <a asp-action="Index">Retornar para a Lista</a>
        </form>    
    </body>
</html>

Tarefas/Views/Tarefas/Edit.cshtml
@model TarefaItem

<html>
    <head>
        <meta name="viewport" content="width=device-width"/>
        <title>Editar tarefa</title>
    </head>

    <body>
        <h4>Editar Tarefa</h4>
        <hr/>

        <div class="row">
            <div class="col-md-4">
                <form asp-action="Edit">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>

                    <input type="hidden" asp-for="Id"/>

                    <div class="form-group">
                        <div class="check-box">
                            <label>
                                <input asp-for="EstaCompleta"/> @Html.DisplayNameFor(model => model.EstaCompleta)
                            </label>
                        </div>
                    </div>

                    <div class="form-group">
                        <label asp-for="Nome" class="control-label"></label>
                        <input asp-for="Nome" class="form-control"/>
                        @*Este atributo asp-validation-for serve para validar os atributos especificados*@
                        @*Os erros serão exibidos de acordo com os data annotations*@
                        <span asp-validation-for="Nome" class="text-danger"></span>
                    </div>

                    <div class="form-group">
                        <label asp-for="DataConclusao" class="control-label"></label>
                        <input asp-for="DataConclusao" class="form-control"/>
                        <span asp-validation-for="DataConclusao" class="text-danger"></span>
                    </div>

                    <div class="form-group">
                        <input type="submit" value="Salvar alteração" class="btn btn-default"/>
                    </div>
                </form>
            </div>
        </div>

        <div>
            <a asp-action="Index">Retornar para a lista</a>
        </div>
    </body>
</html>

Tarefas/Views/Tarefas/Index.cshtml
@model TarefaViewModel;

<div class="panel panel-default tarefa-panel">
    <div class="panel-heading">@ViewData["Title"]</div>

    <table class="table table-hover">
        <thead>
            <tr>
                <td>&#x2714;</td>
                <td>Tarefa</td>
                <td>Previsão</td>
            </tr>
            </thead>
            <tbody>
                @foreach(var tarefa in Model.TarefaItens){
                    <tr>
                        <td><input type="checkbox" name="@tarefa.Id" value="true" checked="@tarefa.EstaCompleta" class="done-checkbox"></td>
                        <td>@tarefa.Nome</td>
                        <td>@String.Format("{0:dd/MM/yyyy}",@tarefa.DataConclusao)</td>
                        <td>
                            <a asp-action="Edit" asp-route-id="@tarefa.Id">Editar</a> |
                            <a asp-action="Delete" asp-route-id="@tarefa.Id">Deletar</a>
                        </td>
                    </tr>
                }           
            </tbody>
    </table>

    <div class="panel-footer add-item-form">
        <form asp-controller="Tarefas" asp-action="AdicionarItemTarefa" method="GET">
            <button type="submit" id="add-item-button" class="btn-success">Incluir nova tarefa</button>
        </form>
    </div>
</div>
    